### ISSUE TITLE
Handle operation request

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/wlm-server#21]
### Feature you want to implement
This is related to operate the channels and maintain the connection with WLM.

If even one user requests to operate a certain channel, the channel would be turned on, i.e., be measured.
In addition, if even one user requests to operate any channel, WLM would be started.

### How the feature is implemented
*TBD*

### Additional context
*TBD*

**Comment by BECATRUE** [comment]
I already handled this in #31, hence I close the issue.

**Comment by kangz12345** [comment]
How about closing this as completed, as you already completed this issue?
